<a href="https://colab.research.google.com/github/Sanju1403/pytorch_tutorial/blob/main/lec_2_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
my_list = [1, 2, 3, 4, 5]     # 1D array
my_list

[1, 2, 3, 4, 5]

In [3]:
my_list2 = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]    # Multi-dimensional array
my_list2

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [4]:
# Numpy Array

np1 = np.random.rand(3, 4)
np1

array([[0.43224419, 0.62151956, 0.83001919, 0.88330934],
       [0.51676709, 0.46598484, 0.97317986, 0.56547943],
       [0.67347602, 0.81084444, 0.41824213, 0.77253817]])

In [5]:
np1.dtype

dtype('float64')

In [6]:
np_1 = np.random.rand(3)
np_1

array([0.65139581, 0.03395661, 0.52591628])

In [12]:
# TENSORS

tensor_2D = torch.rand(3, 4)
tensor_2D
# tensor_2D.dtype

tensor([[0.4707, 0.0660, 0.1733, 0.8660],
        [0.1806, 0.9940, 0.8341, 0.1381],
        [0.3639, 0.4297, 0.0414, 0.4121]])

In [9]:
tensor_3D = torch.zeros(2, 3, 4)
tensor_3D

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
## Create tensor out of numpy array

my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.4322, 0.6215, 0.8300, 0.8833],
        [0.5168, 0.4660, 0.9732, 0.5655],
        [0.6735, 0.8108, 0.4182, 0.7725]], dtype=torch.float64)